### ISSUE TITLE
PyTorch and Apex version

### ISSUE THREAD

**Issue by Soumyaworks** [sem2vec/sem2vec-BERT#1]
Hi,

I am trying to setup sem2vec-BERT based on the instructions given in `README`. This builds docker image with 1.8 version of PyTorch. However, running RoBERTa model by executing python `src/run_roberta.py` is giving `AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'` since the APIs have been updated in the recent versions of PyTorch.

To fix this I downgraded torch version to 1.6.0. But the cuda version is causing an issue. It would be of great help if you could provide the exact versions of pytorch, the dependencies and the particular apex checkpoint which was used during cloning so that we can get a working setup.

**Comment by whj0401** [comment]
You could try to install the environment with a venv and install a newer version pytorch.
`torch==1.13` with a compatible `transformers` should be fine. Please contact me if you have any other questions.

**Comment by Soumyaworks** [comment]
Thank you, its working without using apex. 

Also, I observed that the repo provides a sample dataset. Would it be possible to get access to the full dataset that was used in the paper?

**Comment by whj0401** [comment]
These projects are well-maintained and easy to compile. It should be OK if you compile these binaries yourself.
In terms of the `Tigress` cases, they can only be compiled on an old linux distribution (I remember I use an ubuntu 14.04 docker container).
I just uploaded the link of these [Tigress samples](https://drive.google.com/file/d/1i0w4Y_8cPuseU5eHr4ZSFKwp1LsMhfSc/view?usp=sharing).

**Comment by Soumyaworks** [comment]
Okay, thank you for your help in this.
